version: '3'
services:
  app:
    build: app/
    ports:
      - '5000:5000'
    volumes:
      - './app:/app'
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=bank
    restart: always

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank
    volumes:
      - './db:/docker-entrypoint-initdb.d'
    restart: always
